services:
  - type: web
    name: prototipo-web
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: prototipo-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SENDGRID_API_KEY
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: DISCORD_WEBHOOK_URL
        sync: false

  - type: psql
    name: prototipo-db
    plan: free
